Auto-detect lines
Minor changes

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -34,24 +34,25 @@ runs:
       shell: bash
       run: |
         # Downloading ShellCheck...
-        annotate_error() { echo "::error file=action.yml,line=$2,col=1,endColumn=50::Error $1 on line $2"; exit "$1"; }
+        BASE_LINE='37'
+        annotate_error() { LINE="$(("${BASH_LINENO[0]}"+"${BASE_LINE}"-2))"; echo "::error::Error $1 in action.yml at line ${LINE}"; exit "$1"; }
 
-        case "${{ runner.os }}" in 'Linux') current_os='linux';; 'macOS') current_os='darwin';; 'Windows') current_os='win';; *) annotate_error 1 39; esac
+        case "${{ runner.os }}" in 'Linux') current_os='linux';; 'macOS') current_os='darwin';; 'Windows') current_os='win';; *) annotate_error 1; esac
         action_path="${{ github.action_path }}"
         sc_ver="${{ inputs.shellcheck-version }}"
         base_url="https://github.com/koalaman/shellcheck/releases/download/${sc_ver?}/"
         if test "${current_os}" = 'win'; then archive_name="shellcheck-${sc_ver?}.zip"; else archive_name="shellcheck-${sc_ver?}.${current_os?}.x86_64.tar.xz"; fi
 
         ## Installing wget (only on Windows)...
-        if test "${current_os}" = 'win'; then choco install --no-progress --yes wget 1>/dev/null || annotate_error 2 46; fi
+        if test "${current_os}" = 'win'; then choco install --no-progress --yes wget 1>/dev/null || annotate_error 2; fi
 
-        wget -q -O "${archive_name?}" "${base_url?}${archive_name?}" || annotate_error 3 48
+        wget -q -O "${archive_name?}" "${base_url?}${archive_name?}" || annotate_error 3
         if test "${current_os}" = 'win'; then
-          unzip -ojq "${archive_name?}" '*' -d "./shellcheck-${sc_ver?}/" || annotate_error 4 50
+          unzip -ojq "${archive_name?}" '*' -d "./shellcheck-${sc_ver?}/" || annotate_error 4
         else
-          tar -xf "${archive_name?}" || annotate_error 4 52
+          tar -xf "${archive_name?}" || annotate_error 4
         fi
-        mv -f "./shellcheck-${sc_ver?}/shellcheck"* "${action_path?}/" || annotate_error 5 54
+        mv -f "./shellcheck-${sc_ver?}/shellcheck"* "${action_path?}/" || annotate_error 5
         rm -f "./${archive_name?}"; rm -rf "./shellcheck-${sc_ver?}"
     - name: "Display ShellCheck version"
       shell: bash
@@ -76,7 +77,7 @@ runs:
           IFS="$OLDIFS"
         fi
 
-        scan_file()
+        scan_files()
         {
           files_with_issues='0'
           while read -r FILE; do
@@ -91,8 +92,9 @@ runs:
               echo "Ignored: $FILE"
             elif expr "$FILE_LOWER" : '^.*\.\(sh\|bash\|ash\|dash\|ksh\)$' 1>/dev/null || test '#!' = "$(head -c 2 "$FILE")"; then
               echo "Currently scanning: $FILE"
+              set -o pipefail
               if test "${{ runner.os }}" = 'Windows'; then
-                "${{ github.action_path }}/shellcheck" "${sc_params[@]}" "$FILE" | tr -d '\r'; STATUS="${PIPESTATUS[0]}"
+                "${{ github.action_path }}/shellcheck" "${sc_params[@]}" "$FILE" | tr -d '\r'; STATUS="$?"
               else
                 "${{ github.action_path }}/shellcheck" "${sc_params[@]}" "$FILE"; STATUS="$?"
               fi
@@ -103,7 +105,12 @@ runs:
           done
           return "${files_with_issues}"
         }
-        find '.' -type f \! -path './.git/*' | LC_ALL=C sort | scan_file; files_with_issues="$?"
+        find '.' -type f \! -path './.git/*' | LC_ALL=C sort | scan_files; files_with_issues="$?"
 
-        echo "Files with issues: ${files_with_issues}"
+        printf '################################################################################\n\n'
+        if test "${files_with_issues}" -gt '0'; then
+          echo "::error::Files with issues: ${files_with_issues}"
+        else
+          echo "::notice::Files with issues: ${files_with_issues}"
+        fi
         exit "${files_with_issues}"
